version: "3"

services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "America/Detroit"
      WEBPASSWORD: "${WEB_PASSWORD}"
    volumes:
      - ./config/:/etc/pihole/
      - ./dnsmasq/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
