version: "3"

services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: "America/Detroit"
      WEBPASSWORD: "${WEB_PASSWORD}"
      ServerIP: "192.168.2.4"
    volumes:
      - ./config/:/etc/pihole/
      - ./dnsmasq/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
